### ISSUE TITLE
MAEV2 feature

### ISSUE THREAD

**Issue by ClancyAyres** [dingfengshi/tridetplus#1]
Hello, author, can you share the dataset features you extracted using the MAEV2 model? Thank you

**Comment by dingfengshi** [comment]
> Hello, author, can you share the dataset features you extracted using the MAEV2 model? Thank you

Hi, for the THUMOS14 dataset, you can download the official feature from VideoMAEv2 repo. I will release the feature for the HACS dataset, but it's large and may take a few days. Please keep attention for that, thank you!

**Comment by dingfengshi** [comment]
Hi, the features of HACS have been released, please see the ```readme.md``` for more details.
