### ISSUE TITLE
Feature of charades 

### ISSUE THREAD

**Issue by PeterJoe15** [dingfengshi/tridetplus#3]
Hello, very excellent work! I have a question. Why is the feature of charades in the paper I3D, while the official feature you provided is fc7.

**Comment by dingfengshi** [comment]
Thank you very much for pointing out the issue. I have checked the implementation of the official features, and the features we use should be the RGB branch in the two-stream convolutional network, specifically a VGG network. We will revise the description of this part in the paper.

**Comment by PeterJoe15** [comment]
Thank you for your reply

**Comment by dingfengshi** [comment]
Hi, sorry for the mistake in my previous reply, we use our own extracted I3D features in our paper and we have updated the link to the features in the README.md. We're sorry if it caused you any inconvenience.
