### ISSUE TITLE
Can you share the I3D feature of Charades?

### ISSUE THREAD

**Issue by sming256** [dingfengshi/tridetplus#7]
Thanks for your great work.

In the charades' [config file](https://github.com/dingfengshi/tridetplus/blob/main/configs/charades_i3d.yaml),  you mentioned I3D feature is used. Can you share this I3D feature?

Thanks!

**Comment by dingfengshi** [comment]
Hi, I apologize for the mistake. The feature is the official feature of the Two-Stream Convolution Network. I will update the description in the paper soon.

**Comment by sming256** [comment]
Thanks for the reply!

I noticed that the official RGB feature has a dimension of 4096. Do you directly use this feature? Or do we need some extra steps to preprocess the feature?

**Comment by dingfengshi** [comment]
Many thanks for your reminders, I have rechecked my backup files and found my answer wrong, our experiments indeed used the I3D features we extracted (about 6G), which I will upload later. If you are in a hurry you can email me and we can figure out a faster way to transfer them.

**Comment by sming256** [comment]
I am not in a hurry. Thanks again for sharing it!

**Comment by dingfengshi** [comment]
The features are uploaded, please see REAMME.md for the feature details.
